using System;
using System.Collections.Generic;
using System.Text;

namespace SQLBulk.Models
{
    public class PrimaryKey
    {
        public string ColumnName { get; set; }
        public bool AutoGenerated { get; set; }
    }
}
