using SQLBulk.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace SQLBulk.Options
{
    public class BulkOptions
    {
        /// <summary>
        /// SqlBulkCopy batch size.
        /// </summary>
        public int BatchSize { get; set; } = 0;
        /// <summary>
        /// If your complete primary key is auto generated. If you have a Primary Key which consist of multiple columns with are not all auto generated you should use attributes.
        /// </summary>
        public bool? AutoGeneratedPK { get; set; } = null;
        public string DestinationTableName { get; set; } = string.Empty;
        /// <summary>
        /// Specify primary key. Not needed if you're using attributes.
        /// </summary>
        public PrimaryKey[] PrimaryKeys { get; set; } = new PrimaryKey[0];
        public int SqlBulkCopyTimeoutInSeconds { get; set; } = 120;
    }
}
