using SQLBulk.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace SQLBulk.Options
{
    public class BulkOptions
    {
        public int BatchSize { get; set; } = 0;
        public bool? AutoGeneratedPK { get; set; } = null;
        public string DestinationTableName { get; set; } = string.Empty;
        public PrimaryKey[] PrimaryKeys { get; set; } = new PrimaryKey[0];
        public int SqlBulkCopyTimeoutInSeconds { get; set; } = 120;
    }
}
